<!DOCTYPE html>
<html lang="en">
<head>
    <?php
        session_start();    
        require_once 'config/db.php'; // Fixed the path to avoid directory errors

        if (!isset($_SESSION['user_id'])) {
            header('Location: login.php');
            exit;
        }

        $selected_tag = isset($_GET['tag']) ? htmlspecialchars(trim($_GET['tag'])) : '';

        $recipes = [];
        $error_msg = "";

        // V2 update: Query the View instead of the raw table so we get the pre-formatted dietary_tags
        $sql = "SELECT DISTINCT r.* FROM recipes r
                LEFT JOIN recipe_ingredients ri ON r.recipe_id = ri.recipe_id
                LEFT JOIN ingredient_allergens ia ON ia.ingredient_id = ri.ingredient_id
                LEFT JOIN allergens a ON a.allergen_id = ia.allergen_id WHERE ";

        // V2 update: Added deleted_at IS NULL to hide soft-deleted recipes
        $where_clauses = ["r.deleted_at IS NULL", "r.submitted_by = ?"];
        $params = [$_SESSION['user_id']];

        // If they click a sidebar tag (like Vegan), apply that filter
        if (!empty($selected_tag)) {
            // These 3 tags map directly to negative Allergen filters
            if (in_array($selected_tag, ['Nut-Free', 'Gluten-Free', 'Dairy-Free'])) {
                
                $allergen_map = [
                    'Nut-Free' => 'Nuts',
                    'Gluten-Free' => 'Gluten',
                    'Dairy-Free' => 'Dairy'
                ];
                $target_allergen = $allergen_map[$selected_tag];

                // V2 update: Exclude recipes that contain ingredients linked to this specific allergen
                $where_clauses[] = "r.recipe_id NOT IN (
                    SELECT ri.recipe_id 
                    FROM recipe_ingredients ri
                    INNER JOIN ingredient_allergens ia ON ia.ingredient_id = ri.ingredient_id
                    INNER JOIN allergens a ON a.allergen_id = ia.allergen_id
                    WHERE a.allergen_name = ?
                )";
                $params[] = $target_allergen;

            } else {
                // INCLUSION: For Vegan, Vegetarian, Halal, Keto, and Paleo
                // V2 update: Just search the concatenated tags column generated by the View
                $where_clauses[] = "r.dietary_tags LIKE ?";
                $params[] = "%" . $selected_tag . "%";
            }
        }

        $sql .= implode(" AND ", $where_clauses);

        // PDO: prepare once, then execute with the full $params array
        try {
            $stmt = $pdo->prepare($sql);
            $stmt->execute($params);
            while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
                $recipes[] = $row;
            }
            $stmt = null;
        } catch (PDOException $e) {
            $error_msg = "Database error: " . $e->getMessage();
        }

        $approved_recipes = array_filter($recipes, fn($r) => $r['status'] === 'approved');
        $rejected_recipes = array_filter($recipes, fn($r) => $r['status'] === 'rejected');

        $title = "MealMate - My Recipes";
        include_once 'includes/header.php';
        require_once 'helper/get-image-link.php';
    ?>
    <link rel="stylesheet" href="assets/css/recipes.css">
</head>
<body>
    <?php include_once 'includes/nav.php'; ?>

    <div class="container-fluid px-4 mt-3">
        <div>
            <div class="d-flex flex-row justify-content-between align-items-center">
                <h2 class="mb-4">
                    All Approved Recipes
                </h2>
                <a href="submit-recipe.php" class="btn btn-primary text-nowrap flex-shrink-0">Add Recipe</a>
            </div>

            <?php if (!empty($error_msg)): ?>
                <div class="alert alert-danger"><?php echo $error_msg; ?></div>
            <?php endif; ?>

            <div class="row">
                <?php if (empty($approved_recipes) && empty($error_msg)): ?>
                    <div class="col-12">
                        <div class="alert alert-info">
                            No approved recipes found. Either it is pending approvel, rejected, or you can submit your first at <a href="submit-recipe.php" class="alert-link">Submit Recipe</a>!
                        </div>
                    </div>
                <?php else: ?>
                    
                    <?php foreach ($approved_recipes as $recipe): ?>
                        <div class="col-md-6 col-lg-4 mb-4">
                            <div class="card h-100 shadow-sm">
                                <div class="rounded-top overflow-hidden recipe-images">
                                    <img src="<?= htmlspecialchars(getImageLink($recipe['title'], $recipe['recipe_id'])) ?>" alt="<?= htmlspecialchars($recipe['title']) ?>" style="width:100%; height:100%; object-fit:cover;">
                                </div>
                                <div class="card-body d-flex flex-column">
                                    <h5 class="card-title"><?php echo htmlspecialchars($recipe['title']); ?></h5>
                                    
                                    <p class="card-text text-primary small mb-1 fw-bold">
                                        <?php echo htmlspecialchars($recipe['dietary_tags'] ?? ''); ?>
                                    </p>

                                    <p class="card-text text-muted small mb-2">
                                        Prep Time: <?php echo htmlspecialchars($recipe['prep_time_min']); ?> mins
                                    </p>
                                    <p class="card-text flex-grow-1">
                                        <?php echo htmlspecialchars(substr($recipe['description'] ?? 'No description available.', 0, 75)) . '...'; ?>
                                    </p>
                                    <a href="recipe-detail.php?id=<?php echo $recipe['recipe_id']; ?>" class="btn btn-outline-primary mt-auto">View Full Recipe</a>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                    
                <?php endif; ?>
            </div>
        </div>
    </div>

    <div class="container-fluid px-4 mt-3">
        <div class="">
            <h2 class="mb-4">
                All Rejected Recipes
            </h2>

            <?php if (!empty($error_msg)): ?>
                <div class="alert alert-danger"><?php echo $error_msg; ?></div>
            <?php endif; ?>

            <div class="row">
                <?php if (empty($rejected_recipes) && empty($error_msg)): ?>
                    <div class="col-12">
                        <div class="alert alert-info">
                            No rejected recipes.
                        </div>
                    </div>
                <?php else: ?>
                    
                    <?php foreach ($rejected_recipes as $recipe): ?>
                        <div class="col-md-6 col-lg-4 mb-4">
                            <div class="card h-100 shadow-sm">
                                <div class="rounded-top overflow-hidden recipe-images">
                                    <img src="<?= htmlspecialchars(getImageLink($recipe['title'], $recipe['recipe_id'])) ?>" alt="<?= htmlspecialchars($recipe['title']) ?>" style="width:100%; height:100%; object-fit:cover;">
                                </div>
                                <div class="card-body d-flex flex-column">
                                    <h5 class="card-title"><?php echo htmlspecialchars($recipe['title']); ?></h5>
                                    
                                    <p class="card-text text-primary small mb-1 fw-bold">
                                        <?php echo htmlspecialchars($recipe['dietary_tags'] ?? ''); ?>
                                    </p>

                                    <p class="card-text text-muted small mb-2">
                                        Prep Time: <?php echo htmlspecialchars($recipe['prep_time_min']); ?> mins
                                    </p>
                                    <p class="card-text flex-grow-1">
                                        <?php echo htmlspecialchars(substr($recipe['description'] ?? 'No description available.', 0, 75)) . '...'; ?>
                                    </p>
                                    <a href="recipe-detail.php?id=<?php echo $recipe['recipe_id']; ?>" class="btn btn-outline-primary mt-auto">View Full Recipe</a>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                    
                <?php endif; ?>
            </div>
        </div>
    </div>

    <?php include_once 'includes/footer.php'; ?>
</body>
</html>