<?php
session_start();    

require_once '../config/db.php'; // Fixed the path to avoid directory errors

$selected_tag = isset($_GET['tag']) ? htmlspecialchars(trim($_GET['tag'])) : '';

$recipes = [];
$error_msg = "";

// V2 update: Query the View instead of the raw table so we get the pre-formatted dietary_tags
$sql = "SELECT DISTINCT r.* FROM v_recipe_summary r";

// V2 update: Added deleted_at IS NULL to hide soft-deleted recipes
$where_clauses = ["r.status = 'approved'", "r.deleted_at IS NULL"];
$params = [];

// If they click a sidebar tag (like Vegan), apply that filter
if (!empty($selected_tag)) {
    // These 3 tags map directly to negative Allergen filters
    if (in_array($selected_tag, ['Nut-Free', 'Gluten-Free', 'Dairy-Free'])) {
        
        $allergen_map = [
            'Nut-Free' => 'Nuts',
            'Gluten-Free' => 'Gluten',
            'Dairy-Free' => 'Dairy'
        ];
        $target_allergen = $allergen_map[$selected_tag];

        // V2 update: Exclude recipes that contain ingredients linked to this specific allergen
        $where_clauses[] = "r.recipe_id NOT IN (
            SELECT ri.recipe_id 
            FROM recipe_ingredients ri
            INNER JOIN ingredient_allergens ia ON ia.ingredient_id = ri.ingredient_id
            INNER JOIN allergens a ON a.allergen_id = ia.allergen_id
            WHERE a.allergen_name = ?
        )";
        $params[] = $target_allergen;

    } else {
        // INCLUSION: For Vegan, Vegetarian, Halal, Keto, and Paleo
        // V2 update: Just search the concatenated tags column generated by the View
        $where_clauses[] = "r.dietary_tags LIKE ?";
        $params[] = "%" . $selected_tag . "%";
    }
}

$sql .= " WHERE " . implode(" AND ", $where_clauses);

// PDO: prepare once, then execute with the full $params array
try {
    $stmt = $pdo->prepare($sql);
    $stmt->execute($params);
    while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
        $recipes[] = $row;
    }
    $stmt = null;
} catch (PDOException $e) {
    $error_msg = "Database error: " . $e->getMessage();
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Browse Recipes - MealMate</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .list-group-item.active {
            background-color: #0d6efd;
            border-color: #0d6efd;
        }
    </style>
</head>
<body class="bg-light">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
    <div class="container">
        <a class="navbar-brand" href="index.php">MealMate</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item"><a class="nav-link active" href="recipes.php">Browse All</a></li>
                <li class="nav-item"><a class="nav-link" href="search.php">Search</a></li>
                <li class="nav-item"><a class="nav-link" href="submit-recipe.php">Submit Recipe</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container mb-5">
    <div class="row">
        
        <div class="col-md-3 mb-4">
            <div class="card shadow-sm">
                <div class="card-header bg-white">
                    <h5 class="mb-0">Filter by Diet</h5>
                </div>
                <div class="list-group list-group-flush">
                    <a href="recipes.php" class="list-group-item list-group-item-action <?php echo empty($selected_tag) ? 'active' : ''; ?>">
                        All Recipes
                    </a>
                    <a href="recipes.php?tag=Gluten-Free" class="list-group-item list-group-item-action <?php echo ($selected_tag == 'Gluten-Free') ? 'active' : ''; ?>">
                        Gluten-Free
                    </a>
                    <a href="recipes.php?tag=Vegan" class="list-group-item list-group-item-action <?php echo ($selected_tag == 'Vegan') ? 'active' : ''; ?>">
                        Vegan
                    </a>
                    <a href="recipes.php?tag=Vegetarian" class="list-group-item list-group-item-action <?php echo ($selected_tag == 'Vegetarian') ? 'active' : ''; ?>">
                        Vegetarian
                    </a>
                    <a href="recipes.php?tag=Nut-Free" class="list-group-item list-group-item-action <?php echo ($selected_tag == 'Nut-Free') ? 'active' : ''; ?>">
                        Nut-Free
                    </a>
                    <a href="recipes.php?tag=Halal" class="list-group-item list-group-item-action <?php echo ($selected_tag == 'Halal') ? 'active' : ''; ?>">
                        Halal
                    </a>
                    <a href="recipes.php?tag=Dairy-Free" class="list-group-item list-group-item-action <?php echo ($selected_tag == 'Dairy-Free') ? 'active' : ''; ?>">
                        Dairy-Free
                    </a>
                    <a href="recipes.php?tag=Keto" class="list-group-item list-group-item-action <?php echo ($selected_tag == 'Keto') ? 'active' : ''; ?>">
                        Keto
                    </a>
                    <a href="recipes.php?tag=Paleo" class="list-group-item list-group-item-action <?php echo ($selected_tag == 'Paleo') ? 'active' : ''; ?>">
                        Paleo
                    </a>
                </div>
            </div>
        </div>

        <div class="col-md-9">
            <h2 class="mb-4">
                <?php 
                if (!empty($selected_tag)) {
                    echo htmlspecialchars($selected_tag) . " Recipes";
                } else {
                    echo "All Approved Recipes";
                }
                ?>
            </h2>

            <?php if (!empty($error_msg)): ?>
                <div class="alert alert-danger"><?php echo $error_msg; ?></div>
            <?php endif; ?>

            <div class="row">
                <?php if (empty($recipes) && empty($error_msg)): ?>
                    <div class="col-12">
                        <div class="alert alert-info">
                            No recipes found for this category. Be the first to <a href="submit-recipe.php" class="alert-link">submit one</a>!
                        </div>
                    </div>
                <?php else: ?>
                    
                    <?php foreach ($recipes as $recipe): ?>
                        <div class="col-md-6 col-lg-4 mb-4">
                            <div class="card h-100 shadow-sm">
                                <div class="bg-secondary text-white text-center py-5 rounded-top">
                                    <span>Image Placeholder</span>
                                </div>
                                <div class="card-body d-flex flex-column">
                                    <h5 class="card-title"><?php echo htmlspecialchars($recipe['title']); ?></h5>
                                    
                                    <p class="card-text text-primary small mb-1 fw-bold">
                                        <?php echo htmlspecialchars($recipe['dietary_tags'] ?? ''); ?>
                                    </p>

                                    <p class="card-text text-muted small mb-2">
                                        Prep Time: <?php echo htmlspecialchars($recipe['prep_time_min']); ?> mins
                                    </p>
                                    <p class="card-text flex-grow-1">
                                        <?php echo htmlspecialchars(substr($recipe['description'] ?? 'No description available.', 0, 75)) . '...'; ?>
                                    </p>
                                    <a href="recipe-detail.php?id=<?php echo $recipe['recipe_id']; ?>" class="btn btn-outline-primary mt-auto">View Full Recipe</a>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                    
                <?php endif; ?>
            </div>
        </div>

    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>